### ISSUE TITLE
Develop UI for Search Ranking

### ISSUE THREAD

**Issue by habib535** [StarcounterApps/Search#13]
As an Admin I want to have an interface where I can add/remove keywords related to the search pinning. User should be able to search any company / concept and then can add different type (Boost & Eliminate) of related keywords. In addition user should also have the ability to provide the **Top** value e.g. a specific company needs to be displayed in the top 2 search results whenever curtain keyword matches.

**Comment by warpech** [comment]
As discussed in https://github.com/Starcounter/Minutes/issues/69, the authorization to this page can be done using the [Authorization](https://github.com/starcounter/authorization) library. 

Our reference implementations are in repos:

- https://github.com/StarcounterApps/Images (more complex)
- https://github.com/StarcounterApps/Calendar (less complex)

@un-tone will add comments in code to explain the patterns used. Later, @un-tone will draft a Cookbook article about using the authorization library.

**Comment by habib535** [comment]
This is working fine on inside.starcounter.com now. 
The following requires a user to be part of the `Admin (System Users)` group
```
/search/ranking
/search/settings 
```
Other pages requires a user to be logged-in
