### ISSUE TITLE
Search input field disables click morphing

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Search#14]
PuppetJs has a feature of detecting clicks inside the web app. If the link is within the app, the page is **morphed** to a page, instead of doing a full page reload.

However, the following lines in https://github.com/StarcounterApps/Search/blob/develop/src/Search/wwwroot/Search/viewmodels/InstantSearch.html#L107-L109 disable that feature, turning the `<a>` element inside typeahead results into regular links.

You can test it by noticing that clicking on a search result results in a full page reload:

![bug](https://user-images.githubusercontent.com/566463/28316590-bc337e06-6bc3-11e7-9a13-89862103b5d9.gif)

Compare this with any other link in the app:

![no-bug](https://user-images.githubusercontent.com/566463/28316596-c422c388-6bc3-11e7-8ce2-04920f7592e8.gif)

**Comment by warpech** [comment]
Can this be closed now?

**Comment by habib535** [comment]
This is working fine on inside.starcounter.com now. Closing..
