### ISSUE TITLE
No information when user is not signed in.

### ISSUE THREAD

**Issue by PatrykSzwer** [StarcounterApps/Search#23]
### Steps to reproduce
1. Sign off or don't turn on signIn app.
2. Go to http://localhost:8080/search
### Expected result
An information about lack of permission.

### Actual result
Blank page.

### Technical information
This issue happens only in Chrome, Firefox and Edge shows correct information.
##### Browsers affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge

**Comment by habib535** [comment]
This is auto fixed :) I tried and was unable to reproduce.

**Comment by PatrykSzwer** [comment]
Checked, It's working now. Closing.
