### ISSUE TITLE
SearchAll page shouldn't have the dropdrown if there's only one option

### ISSUE THREAD

**Issue by Mihaiii** [StarcounterApps/Search#26]
SearchAll page shouldn't have the dropdrown if there's only one option

### Screenshot

![searchall](https://user-images.githubusercontent.com/8951553/30486008-10aa2c2a-99e4-11e7-9f2e-b6d0dd4fffc4.png)

**Comment by habib535** [comment]
@Mihaiii thank you for reporting the issue. This is fixed, please verify!

**Comment by Mihaiii** [comment]
Thanks! :)
Closing as done.
