### ISSUE TITLE
CSS update

### ISSUE THREAD

**Issue by Mihaiii** [StarcounterApps/Search#30]
@habib535 Please update the CSS so that everything will take into the consideration the parent container. I need to blend search results into a side panel and the result looks like this:
<img width="787" alt="searchcontent" src="https://user-images.githubusercontent.com/8951553/31266557-a0920790-aa74-11e7-8b48-7ef23b143c42.png">

Also, you can't really notice it in the image, but the font size of the text in the row is too large for this case and there's too much space between rows.

**Comment by habib535** [comment]
Large Screen
___
![capture1](https://user-images.githubusercontent.com/2991381/31287644-36670a2a-aac2-11e7-98f3-56b50845dbc4.PNG)
Medium Screen
___
![capture2](https://user-images.githubusercontent.com/2991381/31287648-38473f5e-aac2-11e7-8a30-b8c2b3b5d072.PNG)
Small Screen
___
![capture3](https://user-images.githubusercontent.com/2991381/31287649-39e0ca74-aac2-11e7-990f-0da341db77c0.PNG)
Extra Small Screen
___
![capture4](https://user-images.githubusercontent.com/2991381/31287651-3b74027a-aac2-11e7-9b04-c520f917f3f7.PNG)

**Comment by habib535** [comment]
Were you able to produce this again?

**Comment by habib535** [comment]
closing as done
