### ISSUE TITLE
Question : Can we search using Email address?

### ISSUE THREAD

**Issue by atifwaqar** [StarcounterApps/Search#32]

**Comment by habib535** [comment]
If you go to `/search/settings` page there you can see the list of searchable `Simplified` models. You can add/remove them based on your requirements. By default it only Search `Simplified.Ring2.Person`, `Simplified.Ring2.Organization`, `Simplified.Ring3.Product` and `Simplified.Ring3.Address`

Please see the below gif for how to make EmailAddress searchable. I know this is a little complicated and will think for how to make it more user-friendly. Please note that once you make the changes you have to restart the Search app again.

![search_email](https://user-images.githubusercontent.com/2991381/31825376-5bf647a6-b5b2-11e7-8f9f-219f158a6340.gif)

**Comment by atifwaqar** [comment]
Thanks @habib535 . This is really good. it helps us a lot.
