### ISSUE TITLE
Implement keyboard arrow navigation for the search input

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Search#4]
To go to the search result from typeahead, it should be possible to:

1. Type your query
2. Click down arrow to highlight the proposed result
3. Press the `Enter` key on the keyboard

Migrated from: https://github.com/StarcounterAppsFreezer/Launcher/issues/173

**Comment by warpech** [comment]
Please make sure that keyboard navigation works in other browsers (Firefox, Edge). I know it is tricky with `dom-bind` event observers. But doable.

**Comment by warpech** [comment]
Can this be closed now?

**Comment by habib535** [comment]
Implemented and deployed
