### ISSUE TITLE
Multiple input fields

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Search#5]
Search app should support more specific input fields. Right now it only supports a single query input.

It should be possible to be more specific and have an advanced search with more fields, for example: advanced people search has separate fields to search in: FirstName, LastName, value of any CustomContactInfo of that person

**Comment by warpech** [comment]
As discussed today with @habib535, we can do it differently: When you want multiple search input fields, you create another app that composes a single query from multiple inputs.

That query then is propagated to the Search app all results page using blending:

```
Handle.GET("/Search/all?query={?}"); //parses the query
Blender.MapUri("/Search/all?query={?}", "search-results")

Handle.GET("/ProjectCsSearch/all?query={?}"); //this is empty
Blender.MapUri("/ProjectCsSearch/all?query={?}", "search-results")
```

What the Search app needs is ability to parse the advanced query, such as:

```
Keyword: [Pizza]  Simplified.Ring2.Organiation.City: [Stockholm]
```

**Comment by habib535** [comment]
Implemented and deployed
Sample URL
`/search/advance?Simplified.Ring2.Person.Name=habib&Simplified.Ring3.Address.city=stockholm`
