### ISSUE TITLE
Configuring the search engine

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Search#6]
We need a way to configure the search engine dynamically through the database configuration, so that I can configure the following principles:

1. Allow searching in the `Organization`
  1. by fuzzy search of properties `Organization.Name`
2. Allow searching in the `Person` class
  1. by fuzzy search in the value of `Person.FirstName`
  2. by fuzzy search in the value of `Person.LastName`
  3. by fuzzy search in the value of any CustomField associated with a Person

I know that 2.3 can be specifically hard to do through configuration, not hardcoded method. @habib535 do you have an idea how to do that?

**Comment by habib535** [comment]
There are two parts in this issue.
1.	Search configuration
2.	Fuzzy Search
 
**Search Configuration**
This can be done via a table in the search app. We can initialize the table (say _SearchEngine.config_) with some default values. Every time a search query arrives we will first read the configuration table values prior to accessing the data.
 
**Fuzzy Search**
If we are going with a simple `like` query then this is not an issue but if the goal here is to search for nearest matching or approximating then this can be as complex as we intend to go for. I will research into some algorithms/libraries for this part.

**Comment by warpech** [comment]
> If we are going with a simple `like` query then this is not an issue but if the goal here is to search for nearest matching or approximating then this can be as complex as we intend to go for. I will research into some algorithms/libraries for this part.

I only meant `like` with wildcards (`%{query}%`), no nearest matching or approximating at this time.

**Comment by warpech** [comment]
The default configuration might be whatever is set now in https://github.com/StarcounterApps/Search/blob/d0dd06085c8a18c7f4770b3547aa1822ffbd969f/src/Search/Helper/SearchProvider.cs#L8-L105

The point of this issue is to replace these hardcoded queries with query builder that is based on a configuration.

**Comment by habib535** [comment]
Everything is configurable now. The following query give us the configurations
`SELECT * FROM Search.SearchEngineConfig`
