### ISSUE TITLE
Pinning of search results

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Search#7]
I would like to influence the position of search results based on some configurable `ResultPriority` property.

So the results on the search result should be sorted on relevance (or your other criteria). On top of that, the results are sorted by `ResultPriority`. 

The results that have equal `ResultPriority` are further shuffled (displayed in random order).

`ResultPriority` is configured per result object, so the same result can have different priority for different keywords.

**Comment by habib535** [comment]
We can create a table that defines all the ranking order for each property inside an object. Will try to implement the same way as #6 

For example a table with following entries will put FirstName matching records on top.

| PropertyName | RankingOrder |
| --- | --- |
| FirstName | 1 |
| LastName | 2 |

Any thoughts?

**Comment by warpech** [comment]
What we need to provide is that for a particular query (`pizza city:Stockholm`) somebody has paid to be displayed as the top 1 (first) result always (even if the relevance says they should be in the middle).

Somebody else have paid to be displayed within the top 5.

**Comment by habib535** [comment]
Implemented and deployed
